[package]
name = "problem005"
version = "0.1.0"
authors = ["Nathan Files <nathanwfiles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde-pickle = "1.0"
